{% set name = "goftests" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/goftests-{{ version }}.tar.gz
  sha256: e6cd0dba04aeb364ee6482277ac08d24d02dc441e764b4088e7d29c468302ffa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy

test:
  imports:
    - goftests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/posterior/goftests
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Goodness of fit tests for general datatypes'
  description: |
    Goftests is intended for unit testing random samplers that generate
    arbitrary plain-old-data, and focuses on robustness rather than
    statistical efficiency. In contrast to scipy.stats and statsmodels,
    goftests does not make assumptions on the distribution being
    tested, and requires only a simple (sample, prob) interface
    provided by MCMC samplers.
  dev_url: https://github.com/posterior/goftests

extra:
  recipe-maintainers:
    - danring
