{% set name = "goftests" %}
{% set version = "0.2.5" %}
{% set sha256 = "90212ba69fca85c5ec8d280a45b475f787fb914a57b2a836fc545c661b182a13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - goftests

about:
  home: https://github.com/posterior/goftests
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Goodness of fit tests for general datatypes'
  description: |
    Goftests is intended for unit testing random samplers that generate
    arbitrary plain-old-data, and focuses on robustness rather than
    statistical efficiency. In contrast to scipy.stats and statsmodels,
    goftests does not make assumptions on the distribution being
    tested, and requires only a simple (sample, prob) interface
    provided by MCMC samplers.
  dev_url: https://github.com/posterior/goftests

extra:
  recipe-maintainers:
    - danring
