travis:
  secure:
    BINSTAR_TOKEN: P35k2LpuItcvCaDdoaWgtXpE62TF4SQ1k0OpzoTAlaM6D+am0MHYme4o79PCgS4OHgv5jNugI8ZCRWMhW3naO+TJGXud4SMzWvh2GxIQU81VXDVAGopWABdiQKq+8XHgHWqXnybz0DzWVHu9Kw08f18ps6LEjZKiKf/EO5xGe5Pvcj93c45zfCPptQxR8V+R8cFSkCZDSzDNL69GToQwJ+219nIPf3xjoMexKyFCKFPK2fOCLgzlWoY564R0kVWoZ5QSaaoH2kBTTR1zwjQufnbi/ScHaYE09Mfhj6aESosVvQQfkILz9UYX6/QpCXp27UWXoAxykE5LR0W4Qgn/rWCuMSv6jxXCcdQFQ5ARs1R7SS7uBdU+8c8T1ulQfLUJG/hbieT5bYJtKmF4bBNSI9Uh/uvXSw4hwr03tPsvVmx4a4I7M+rvyKv4nOPret6VqWcZokfVzkTYlkhkE4IPFWLEel62PZG3II34alHAKdLKW/ySs30p86wQF+So5gYEO52IvGx08IyFEz0YObbBbBkpReB9ont14o2MBeUDa0fvHoeqy0MmW9wSFWamZze5PdUyITdIAMvzos4R/2ch2j1/LzNRj4vuBdcg+EhyBVxkYEsfcwrBSCbCuGFvaPsF+VFEngzrHwVoWHbU8eOGhrLEnjFKXmfow9GmsgsR63k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
