travis:
  secure:
    BINSTAR_TOKEN: ouHpeQSQS8QE6zOMqJ37Qj1xLOk2ZKCzFB7Vbgx2xkoYXrWneGX0oNRkgVdxBsEjrIUIjZswwJAUVC6oMV7iB5osU0tF6dAOA8hVQiECJpStVIXObDVJBlXXkMNlp0zE8aUoUBMOdaDQiymahylq8AcMydc4u2Iuwl5JBvScSRUPv5PHfyhWOB1dKCPyXrvbB/F1Vw2em3FAXYy4jaSMZQSd56xFkZyDh9o+13Ls09EUmCkDh+na+ZPJZ2fZNMrT6ATxvYgSzkO+K97/6xG7Hd6yqrhm99ivuo+RjAZOXEg9ttIlBbVbnmtOAGAdcMhPXp+26rqKz+AW33tllYCZSffAZX9Ov4S6l7B2kN4fK8l6V3X0qPBt2milvgwPVQ0ibsi3TUkEIHubF9vlzLIjR2B9TlR/R0UQFNNNtWZjRoR9JKXm8oCIhUQmH1PjwFmHb0QUCi2mtMDc/9HvONO3sGcDqt9AMabYh1wVaWAJs6sd6Z0ah06Cs6rYf/s8Kz6Ho8sJLsM/53yRd49OTKYkhkHR+Jz32RVt5lk0ZNdZ74/Tq7bjv5FbrALZUz1tQOMTUP0wSxSCoL5ql5+GixSjOjMDJ3Jt3Z88ADtsQAFUM8zi7rNz2IE2O60/rPi8rmIgR5QK22xbJJPYR/eozPPX3fePqejTElrqOXGyOt+JoU4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
